# -*- coding: utf-8 -*-
"""assessment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cj2YyirBR9hmGqSuDcdT0W16G3fvGEDg
"""

#1
length =  float(input("ENTER THE LENGTH : "))
width = float(input("ENTER THE WIDTH : "))

area = length * width
print("THE AREA OF THE RECTANGLE IS ", area)

#2
a = float(input("ENTER WEIGHT in kgs :"))
b = float(input("ENTER HEIGHT in mts"))

BMI = a/(b*b)
print ("YOUR BMI : ", BMI)

#3
students = {}

while True:
    name = input("Enter student name ('done' to finish): ")
    if name.lower() == 'done':
        break
    score = float(input("Enter student score: "))
    students[name] = score

print("\nStudent names and scores:")
for name, score in students.items():
    print(name + ": " + str(score))

#4
a = int(input("ENTER YOU AGE : "))
if a < 18:
  print("YOU ARE MINOR")
elif a >=18:
  print("YOU ARE ADULT")

#5
for i in range(1,51):
  if i%2 == 0:
      print (i)

#6
correct_password = "password123"

while True:
    password = input("Enter the password: ")
    if password == correct_password:
        print("Correct password! Welcome.")
        break
    else:
        print("Incorrect password. Please try again.")

#7
def main(values):
    if not values:
        return 0
    return sum(values) / len(values)

values = [1, 2, 3, 4, 5]
avg = main(values)
print("AVERAGE : ", avg)

#11
def integer_input(prompt):
    while True:
        try:
            num = int(input(prompt))
            return num
        except ValueError:
            print("Error: Please enter an integer.")
num = integer_input("Enter an integer: ")
print("Entered integer:", num)

#10
def add_numbers(num1, num2):
    try:
        result = num1 + num2
        return result
    except TypeError:
        return "Error: Non-numeric inputs provided."
print(add_numbers(5, 'a'))

#8
def count_vowels(text):
    vowels = 'aeiouAEIOU'
    count = 0
    for char in text:
        if char in vowels:
            count += 1
    return count
text = "Hello, World!"
print("Number of vowels:", count_vowels(text))

#9
import datetime

def print_current_datetime():
    current_datetime = datetime.datetime.now()
    print("Current date and time:", current_datetime)


print_current_datetime()

#14
def read_file(filename):
    with open(filename, 'r') as file:
        content = file.read()
    print("Content of the file:", content)

read_file("example.txt")

#13
file_upload = open('/content/sample_data/mnist_test.csv', 'w')

a= []
for i in range (1):
    print("Data to be written to file:: ")
    b = input()
    a.append(b)
file_upload.writelines(a)
file_upload.close()

#15
def enter_new_line(filename, line_to_append):
    with open('/content/sample_data/mnist_test.csv', 'a') as file:
        file.write(line_to_append + '\n')
    with open('/content/sample_data/mnist_test.csv', 'r') as file:
        content = file.read()
    return content

filename = open('/content/sample_data/mnist_test.csv','r')
line_to_append = 'Hello2'
new_content = enter_new_line(filename, line_to_append)
print('\n',new_content)

#12
def divide(dividend, divisor):
    try:
        result = dividend / divisor
        return result
    except ZeroDivisionError:
        return "Error: Division by zero."


print(divide(10, 0))