# -*- coding: utf-8 -*-
"""LVADSUSR99_NANDHA_SP_FA_LAB4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hAP997zW519xpXiQX5_uVpwOxwHnXeVu
"""

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mean_squared_error, precision_score, f1_score, recall_score, confusion_matrix, r2_score
from sklearn.preprocessing import MinMaxScaler
import time
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.cluster import KMeans
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

data = pd.read_csv('social_network.csv')
data.info()

outlier_model = IsolationForest(contamination=0.1, random_state=42)
outliers = outlier_model.fit_predict(data[['login_activity', 'posting_activity', 'social_connections']])
data['is_outlier'] = outliers

label_encoder = LabelEncoder()
data['account_status'] = label_encoder.fit_transform(data['account_status'])

fea = ['login_activity', 'posting_activity', 'social_connections']
X = data[fea]
y = data['is_outlier']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = IsolationForest(n_estimators=100, contamination=0.1, max_features=3, max_samples=10000, random_state=42)
model.fit(X_train)

y_pred = model.predict(X_train)

data["anomaly_score"] = model.decision_function(X)

anomalies = data.loc[data["anomaly_score"] < 0]

plt.scatter(data["social_connections"], data["anomaly_score"], label="Not Anomaly")
plt.scatter(anomalies["social_connections"], anomalies["anomaly_score"], color="r", label="Anomaly")
plt.xlabel("Social Connections")
plt.ylabel("Anomaly Score")
plt.legend()
plt.show()